export const courseList = [
	{ nombre: 'DALGO', codigo: 'ISIS-1105', creditos: 3 },
	{ nombre: 'CLE 1', codigo: 'XXXX', creditos: 3 },
	{ nombre: 'CLE 2', codigo: 'XXXX', creditos: 3 },
	{ nombre: 'Introduccion a DISC', codigo: 'ISIS-1001', creditos: 3 },
	{ nombre: 'D.O.O.', codigo: 'ISIS-1226', creditos: 3 },
	{ nombre: 'Física Exp. II', codigo: 'FISI-1029', creditos: 1 },
	{ nombre: 'Electiva Regulada', codigo: 'XXXX', creditos: 3 },
	{ nombre: 'MEL', codigo: 'ISIS-1104', creditos: 3 },
	{ nombre: 'Esc. Universitaria II', codigo: 'LENG-1512', creditos: 2 },
	{ nombre: 'Esc. Universitaria I', codigo: 'LENG-1511', creditos: 2 },
	{ nombre: 'Const. Y Democr', codigo: 'DERE-1300', creditos: 3 },
	{ nombre: 'Cal.Vectorial', codigo: 'MATE-1207', creditos: 3 },
	{ nombre: 'CBU Colombia', codigo: 'CBCC-1177', creditos: 2 },
	{ nombre: 'Cal. Diferencial', codigo: 'MATE-1203', creditos: 3 },
	{ nombre: 'CBU 1', codigo: 'CBXX-XXXX', creditos: 2 },
	{ nombre: 'Estructuras de Datos y Algoritmos', codigo: 'ISIS-1225', creditos: 3 },
	{ nombre: 'Álgebra Lineal', codigo: 'MATE-1105', creditos: 3 },
	{ nombre: 'Arquiemp', codigo: 'ISIS-2403', creditos: 3 },
	{ nombre: 'SW en equipo', codigo: 'ISIS-2603', creditos: 3 },
	{ nombre: 'Química o Biología', codigo: 'QUIM-1103', creditos: 3 },
	{ nombre: 'Física Exp. I', codigo: 'FISI-1019', creditos: 1 },
	{ nombre: 'Cal. Integral Y Ec. Diferenciales', codigo: 'MATE-1214', creditos: 3 },
	{ nombre: 'IP', codigo: 'ISIS-1221', creditos: 3 },
	{ nombre: 'Infracomp', codigo: 'ISIS-2203', creditos: 3 },
	{ nombre: 'Requisito de Idioma', codigo: 'LENG-3999', creditos: 0 },
	{ nombre: 'PMC', codigo: 'ISIS-2007', creditos: 3 },
	{ nombre: 'TI en las organizaciones', codigo: 'ISIS-1404', creditos: 3 },
	{ nombre: 'Lenguajes y Maquinas', codigo: 'ISIS-1106', creditos: 3 },
	{ nombre: 'Física II', codigo: 'FISI-1028', creditos: 3 },
	{ nombre: 'Física I', codigo: 'FISI-1018', creditos: 3 },
	{ nombre: 'Arquisoft', codigo: 'ISIS-2503', creditos: 3 },
	{ nombre: 'Sistrans', codigo: 'ISIS-2304', creditos: 3 },
	{ nombre: 'Lectura en inglés', codigo: 'LENG-2999', creditos: 0 },
	{ nombre: 'Infratec', codigo: 'ISIS-1304', creditos: 3 },
	{ nombre: 'Prob. Y Estadíst. 1', codigo: 'IIND-2106', creditos: 3 },
	{ nombre: 'ANADEC', codigo: 'IIND-2401', creditos: 3 },
	{ nombre: 'Inteligencia de negocios', codigo: 'ISIS-3301', creditos: 3 },
	{ nombre: 'Tecnologias Web', codigo: 'ISIS-3710', creditos: 3 },
	{ nombre: 'Electiva Profesional II', codigo: 'ISIS-3XXX', creditos: 3 },
	{ nombre: 'Infracomu', codigo: 'ISIS-3204', creditos: 3 },
	{ nombre: 'Electiva Profesional I', codigo: 'ISIS-3XXX', creditos: 3 }
];
